version: '3.8'

services:
  gym-postgres:
    image: postgres:16-alpine
    container_name: gym_crm_postgres
    environment:
      POSTGRES_DB: gym_crm_db
      POSTGRES_USER: gym_admin
      POSTGRES_PASSWORD: gym_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gym_admin -d gym_crm_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  gym-crm-app:
    build: .
    container_name: gym_crm_app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=stg # Або dev / prod залежно від потреби
      - STG_DB_URL=jdbc:postgresql://gym-postgres:5432/gym_crm_db
      - STG_DB_USERNAME=gym_admin
      - STG_DB_PASSWORD=gym_password
    depends_on:
      gym-postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata: