spring:
  application:
    name: Gym_CRM
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gym_crm_db
    username: gym_admin
    password: gym_password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

storage:
  init:
    file-path: "classpath:init-data.json"