server:
  port: ${PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

app:
  kafka:
    topics:
      trainer-workload: ${TRAINER_WORKLOAD_TOPIC:trainer-workload-topic}
      trainer-workload-dlt: ${TRAINER_WORKLOAD_DLT_TOPIC:trainer-workload-topic.DLT}
    retry:
      max-attempts: 5
      backoff-interval-ms: 2000

logging:
  level:
    root: WARN
    com.epam.java.specialization.trainer_workload: INFO
    org.springframework.kafka: WARN