server:
  port: ${PORT:8081}

spring:
  kafka:
    bootstrap-servers: ${STG_KAFKA_BOOTSTRAP_SERVERS:kafka-stg:9092}

app:
  kafka:
    topics:
      trainer-workload: ${TRAINER_WORKLOAD_TOPIC:trainer-workload-topic-stg}
      trainer-workload-dlt: ${TRAINER_WORKLOAD_DLT_TOPIC:trainer-workload-topic-stg.DLT}
    retry:
      max-attempts: 3
      backoff-interval-ms: 2000

logging:
  level:
    root: INFO
    com.epam.java.specialization.trainer_workload: INFO
    org.springframework.kafka: INFO