server:
  port: ${PORT:8081}

spring:
  jms:
    broker-url: ${STG_ACTIVEMQ_BROKER_URL:tcp://activemq-stg:61616}
    user: ${STG_ACTIVEMQ_USER:admin}
    password: ${STG_ACTIVEMQ_PASSWORD:admin}

app:
  jms:
    concurrency: 3-5
    queue:
      workload: trainer-workload-queue-stg
      dlq: ActiveMQ.DLQ
    redelivery:
      max-deliveries: 3
      initial-delay: 2000
      back-off-multiplier: 2.0

logging:
  level:
    root: INFO
    com.epam.java.specialization.trainer_workload: INFO
    org.springframework.jms: INFO