server:
  port: ${PORT:8081}

spring:
  application:
    name: trainer-workload-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:trainer-workload-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.epam.java.specialization.common.dto.TrainerWorkloadRequestDto

app:
  kafka:
    topics:
      trainer-workload: ${TRAINER_WORKLOAD_TOPIC:trainer-workload-topic}
      trainer-workload-dlt: ${TRAINER_WORKLOAD_DLT_TOPIC:trainer-workload-topic.DLT}
    retry:
      max-attempts: ${KAFKA_RETRY_MAX_ATTEMPTS:3}
      backoff-interval-ms: ${KAFKA_RETRY_BACKOFF_MS:1000}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "health,info,metrics,prometheus"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true

info:
  app:
    name: "Trainer Workload Microservice"
    description: "Microservice for calculating and storing trainers monthly working hours"
    version: "1.0-SNAPSHOT"