spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}

app:
  kafka:
    topics:
      trainer-workload: ${TRAINER_WORKLOAD_TOPIC:trainer-workload-topic}
      trainer-workload-dlt: ${TRAINER_WORKLOAD_DLT_TOPIC:trainer-workload-topic.DLT}

logging:
  level:
    root: INFO
    com.epam.java.specialization.trainer_workload: DEBUG
    org.springframework.kafka: DEBUG